### ISSUE TITLE
iPhonella navigaatio palkki skaalaa koko sivua

### ISSUE THREAD

**Issue by woltage** [qlma/client#7]
Ennen:
![image](https://cloud.githubusercontent.com/assets/250504/9968307/658a7faa-5e50-11e5-8681-99904c32d34e.png)

Jälkeen:
![image](https://cloud.githubusercontent.com/assets/250504/9968299/597f4d30-5e50-11e5-96a8-186785b34f3d.png)

**Comment by tuomas-tk** [comment]
@jannegylling Haittaako jos tuo navigaatiopalkki ei työnnäkään itse sivun sisältöä oikealle niinkuin on ilmeisesti suunniteltu, vaan vain menee sisällön päälle? Voisin korjata jos ei haittaa :blush:

**Comment by woltage** [comment]
@tuomas-tk anna mennä! Mielestäni se on niin parempi.

**Comment by jannegylling** [comment]
Korjaa vaan! #respect
