### ISSUE TITLE
Yläpalkin menukuvake rivittyy pienillä näytöillä

### ISSUE THREAD

**Issue by tuomas-tk** [qlma/client#8]
![screenshot_2015-09-21-20-07-37](https://cloud.githubusercontent.com/assets/11463784/9999135/659682d8-609d-11e5-9bea-dd14e3d93bc2.jpeg)

Johtuu ilmeisesti style.css tiedoston riveistä 65 & 129, joilla määritetään .name:n leveys. Onko tällä jokin tarkoitus jota en vain huomaa?

**Comment by woltage** [comment]
Tuskimpa, se on varmasti vain bugi :)

**Comment by woltage** [comment]
Awesome! @tuomas-tk 

![image](https://cloud.githubusercontent.com/assets/250504/10028320/694e2980-6174-11e5-8446-f94f7af84d62.png)
